/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PetaniRouteImport } from './routes/petani'
import { Route as IndexRouteImport } from './routes/index'

const PetaniRoute = PetaniRouteImport.update({
  id: '/petani',
  path: '/petani',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/petani': typeof PetaniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/petani': typeof PetaniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/petani': typeof PetaniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/petani'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/petani'
  id: '__root__' | '/' | '/petani'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PetaniRoute: typeof PetaniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/petani': {
      id: '/petani'
      path: '/petani'
      fullPath: '/petani'
      preLoaderRoute: typeof PetaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PetaniRoute: PetaniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
